# fly.toml app configuration file generated for arxiv-research-assistant on 2024-06-10T21:05:48+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'arxiv-research-assistant'
primary_region = 'syd'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
